version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-1.12
      - test-1.13
jobs:
  test-1.12:
    docker:
      - image: 'circleci/golang:1.12'
    steps: &ref_0
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - run: go install ./...
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  test-1.13:
    docker:
      - image: 'circleci/golang:1.13'
    steps: *ref_0
